### ISSUE TITLE
Document COS option 

### ISSUE THREAD

**Issue by leodido** [falcosecurity/falco-website#37]
Because of issue https://github.com/falcosecurity/falco/issues/650 Falco (v0.15.3) introduced a fix for COS via the `KBUILD_EXTRA_CPPFLAGS` env variable and `-DCOS_73_WORKAROUND` option.

**Comment by mfdii** [comment]
I don't think this needs to be documented as it's technically a bug and is fixed in the dev release (and thus the next release).

**Comment by leodido** [comment]
Thus should we close this issue @mfdii ? WDYT

**Comment by ankitjain28may** [comment]
@mfdii It's still not working with the above env-> https://github.com/falcosecurity/falco/issues/650#issuecomment-518620781

**Comment by mfdii** [comment]
This is for Container Optimized OS, not CoreOS
